version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
  deploy:
    steps:
      - run:
        name: Install Now CLI
        command: yarn global add now
      - deploy:
          name: Deploy
          command: now -t $NOW_TOKEN --prod

workflows:
  build-and-test:
    jobs:
      - build-and-test
      - deploy
