defaults: &defaults
  docker:
    - image: circleci/node:latest
  working_directory: ~/tmp/circlci-now

version: 2
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/tmp/circlci-now
      - restore_cache:
          keys:
            - npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
            - npm-cache-{{ .Branch }}
            - npm-cache-
      - run:
          name: NPM Install
          command: npm install
      - save_cache:
          key: npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths: .
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/tmp/circlci-now
      - run:
          name: Install Now CLI
          command: sudo npm install --global --unsafe-perm now
      - deploy:
          name: Deploy & Alias
          command: now --token $NOW_TOKEN --local-config now.json --prod

workflows:
  version: 2
  test-deploy-purge:
    jobs:
      - checkout
      - deploy:
          requires:
            - checkout
